import type { ReactNode } from "react";
import raw from "@/data/phase2Data.json";

// Generated by sickle-plus-plus/export_site_data.py from the run outputs; never hand-edit numbers here.
export const data = raw as any;

// One palette for every Phase 2 chart.
export const COLORS = {
  before: "#d97706", // pretrained checkpoint (zero-shot baseline)
  after: "#16a34a", // fine-tuned checkpoint
  ref: "#0f172a", // predict-the-training-mean reference
  train: "#1e3050",
  val: "#6b8fc7",
  test: "#22c55e",
  grid: "#e5e7eb",
  axis: "#6b7280",
};

// Model identity colours, kept apart from the baseline (amber) / fine-tuned (green) pair.
export const MODEL_COLORS: Record<string, string> = {
  ConvLSTM: "#0f766e",
  "U-TAE": "#1e3050",
  UNet3D: "#9333ea",
};

export const TASKS = [
  { key: "sowing_date", ref: "sowing_date", label: "Sowing date", unit: "days", short: "Sowing" },
  { key: "transplanting_date", ref: "transplanting_date", label: "Transplanting date", unit: "days", short: "Transplanting" },
  { key: "harvesting_date", ref: "harvesting_date", label: "Harvesting date", unit: "days", short: "Harvesting" },
  { key: "crop_yield_as", ref: "crop_yield", label: "Yield (per-field season window)", unit: "kg/ha", short: "Yield (AS)" },
  { key: "crop_yield_rs", ref: "crop_yield", label: "Yield (fixed season window)", unit: "kg/ha", short: "Yield (RS)" },
] as const;

export const fmt = (v: number, unit: string) =>
  unit === "kg/ha" ? Math.round(v).toLocaleString("en-US") : v.toFixed(1);

export const pctChange = (before: number, after: number) => {
  const p = (100 * (after - before)) / before;
  return `${p <= 0 ? "−" : "+"}${Math.abs(p).toFixed(0)}%`;
};

export function Section({ id, eyebrow, title, lede, tone = "sage", children }: {
  id: string; eyebrow?: string; title: string; lede?: ReactNode; tone?: "sage" | "white"; children: ReactNode;
}) {
  return (
    <section
      id={id}
      className={`px-4 py-20 scroll-mt-14 ${tone === "white" ? "bg-white border-y border-gray-100" : "bg-sage-50"}`}
    >
      <div className="max-w-6xl mx-auto">
        {eyebrow && <p className="text-brand-greenDark text-xs font-semibold tracking-widest uppercase">{eyebrow}</p>}
        <h2 className="text-3xl md:text-4xl font-heading font-bold mt-2 mb-3 text-balance">{title}</h2>
        {lede && <div className="text-gray-600 max-w-3xl mb-8">{lede}</div>}
        {children}
      </div>
    </section>
  );
}

export function Card({ title, children, className = "" }: { title?: ReactNode; children: ReactNode; className?: string }) {
  return (
    <div className={`bg-white border border-gray-100 rounded-xl p-6 min-w-0 ${className}`}>
      {title && <h3 className="font-semibold text-navy-900 mb-3">{title}</h3>}
      {children}
    </div>
  );
}

export function Stat({ value, label }: { value: ReactNode; label: string }) {
  return (
    <div className="bg-white border border-gray-100 rounded-xl p-5">
      <div className="font-heading font-bold text-3xl text-navy-900 tabular-nums">{value}</div>
      <div className="text-gray-600 text-sm mt-1">{label}</div>
    </div>
  );
}

export function Legend({ items }: { items: { color: string; label: string; dashed?: boolean }[] }) {
  return (
    <div className="flex flex-wrap gap-x-5 gap-y-1 text-xs text-gray-600">
      {items.map((i) => (
        <span key={i.label} className="inline-flex items-center gap-2">
          {i.dashed ? (
            <span className="inline-block w-5 border-t-2 border-dashed" style={{ borderColor: i.color }} />
          ) : (
            <span className="inline-block w-3 h-3 rounded-sm" style={{ background: i.color }} />
          )}
          {i.label}
        </span>
      ))}
    </div>
  );
}

export const tableWrap = "overflow-x-auto border border-gray-200 rounded-xl bg-white";
export const th = "px-4 py-3 font-semibold";
export const td = "px-4 py-3 text-gray-600 tabular-nums";
export const thead = "bg-sage-100 text-gray-600 text-xs uppercase tracking-widest";
